/**
 * 博客分享功能配置
 */
export const SHARE_CONFIG = {
	/** 水印签名文字 */
	signature: '✨ Written & Generated by Nova with HEART 💗',
	
	/** 是否显示二维码 */
	showQRCode: true,
	
	/** 二维码大小（像素） */
	qrCodeSize: 100,
	
	/** Favicon 路径 */
	faviconPath: '/favicon.png',
	
	/** Favicon 大小（像素） */
	faviconSize: 20,
	
	/** 截图固定宽度（像素）- 确保移动端和桌面端一致 */
	screenshotWidth: 800,
} as const;
